### ISSUE TITLE
Switch to Zarith (was: Pint does not compile with ocaml version 4.07.1)

### ISSUE THREAD

**Issue by adrienrougny** [pauleve/pint#17]
Error during compilation:

ocamlopt -c -I /usr/lib/ocaml/extlib bes.ml
File "bes.ml", line 1:
Error: /usr/lib/ocaml/extlib/extLib.cmi
is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.
make[2]: *** [OCamlMakefile:1010: bes.cmx] Error 2

**Comment by pauleve** [comment]
try `make clean`; whenever ocaml is updated, all the files must be recompiled.

**Comment by adrienrougny** [comment]
I had not recompiled extlib, my bad.

There is another issue: the Big_int module cannot be found anymore, because apparently the num library has become external (and obsolete). Pint compiles when the legacy num library is installed as a dependency and correctly included (in the Makefile of phlib?).
